"""Render the markdown docs into styled HTML pages the dashboard can link to.

    python scripts/render_docs.py

GitHub Pages serves a .md file as a raw download, not a page, so anything the
dashboard links to has to be real HTML. Rather than maintain two copies of the
same prose, the markdown stays canonical and this renders it into the same
Swiss-monochrome shell the rest of the site uses.

Uses markdown-it-py, which is already a dependency of the toolchain here.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from markdown_it import MarkdownIt  # noqa: E402

from loonie.config import ROOT  # noqa: E402

PAGES = [
    ("docs/RESEARCH.md", "docs/research.html",
     "Literature review",
     "Seven works on recursive self-improvement, read against this system"),
]

SHELL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
:root{
  --bg:#000; --line:#1f1f22; --line-2:#2e2e33;
  --fg:#fff; --fg-2:#8d8d96; --fg-3:#82828c; --mark:#ccff00;
  --sans:"Geist",ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif;
  --mono:"Geist Mono",ui-monospace,"SF Mono",Menlo,Consolas,monospace;
  color-scheme:dark;
}
*{box-sizing:border-box;border-radius:0}
html,body{margin:0;background:var(--bg);color:var(--fg)}
body{font:400 16px/1.7 var(--sans);-webkit-font-smoothing:antialiased;
     font-variant-numeric:tabular-nums}
.wrap{max-width:760px;margin:0 auto;padding:0 24px 120px}
.top{display:flex;align-items:baseline;gap:14px;flex-wrap:wrap;
     padding:22px 0 18px;border-bottom:1px solid var(--line);
     font:400 11px/1 var(--mono);letter-spacing:.11em;text-transform:uppercase;
     color:var(--fg-3)}
.top a{color:var(--fg-3);text-decoration:none}
.top a:hover{color:var(--fg)}
.top .sp{flex:1}
header{padding:76px 0 0}
h1{font-size:clamp(30px,5vw,44px);font-weight:300;letter-spacing:-.03em;
   line-height:1.12;margin:0}
.sub{font-size:19px;font-weight:300;color:var(--fg-2);margin:20px 0 0;
     line-height:1.5;letter-spacing:-.01em}
h2{font-size:15px;font-weight:400;letter-spacing:.11em;text-transform:uppercase;
   margin:72px 0 0;padding-bottom:10px;border-bottom:1px solid var(--line-2)}
h3{font-size:17px;font-weight:500;letter-spacing:-.01em;margin:40px 0 0}
p{margin:20px 0 0;color:var(--fg-2)}
strong{color:var(--fg);font-weight:500}
em{color:var(--fg);font-style:italic}
a{color:var(--fg-2);text-decoration:none;border-bottom:1px solid var(--line-2)}
a:hover{color:var(--fg);border-color:var(--fg-2)}
code{font-family:var(--mono);font-size:13.5px;color:var(--fg)}
blockquote{margin:26px 0 0;padding:0 0 0 20px;
           border-left:1px solid var(--line-2);color:var(--fg-2);
           font-size:15.5px;line-height:1.65}
blockquote p{margin-top:0}
blockquote p + p{margin-top:14px}
table{width:100%%;border-collapse:collapse;margin-top:26px;font-size:14px}
th{font:400 10.5px/1.4 var(--mono);letter-spacing:.11em;text-transform:uppercase;
   color:var(--fg-3);text-align:left;padding:0 14px 10px 0;
   border-bottom:1px solid var(--line-2);vertical-align:bottom}
td{padding:12px 14px 12px 0;border-bottom:1px solid var(--line);
   vertical-align:top;color:var(--fg-2)}
td:first-child{color:var(--fg)}
.tw{overflow-x:auto}
ul,ol{margin:20px 0 0;padding-left:22px;color:var(--fg-2)}
li{margin:10px 0}
li::marker{color:var(--fg-3)}
hr{border:0;border-top:1px solid var(--line);margin:56px 0 0}
pre{margin:24px 0 0;padding:20px;border:1px solid var(--line);overflow-x:auto;
    font:400 12.5px/1.75 var(--mono);color:var(--fg-2);background:#050506}
.foot{margin-top:76px;padding-top:22px;border-top:1px solid var(--line);
      font:400 11.5px/1.8 var(--mono);color:var(--fg-3)}
@media(max-width:640px){.wrap{padding:0 16px 80px}}
</style>
</head>
<body><div class="wrap">
<div class="top">
  <span>loonie</span><span class="sp"></span>
  <a href="index.html">dashboard</a>
  <a href="memory.html">grounded memory</a>
</div>
<header><h1>%(h1)s</h1><p class="sub">%(sub)s</p></header>
%(body)s
<div class="foot">Rendered from <code>%(src)s</code>. The markdown is canonical;
this page is generated by <code>scripts/render_docs.py</code>.</div>
</div></body></html>
"""


def main() -> int:
    md = MarkdownIt("commonmark", {"html": True}).enable("table")
    for src, dst, title, sub in PAGES:
        sp, dp = ROOT / src, ROOT / dst
        if not sp.exists():
            print("[docs] missing %s" % src)
            continue
        text = sp.read_text(encoding="utf-8")

        # Drop the leading H1 — the shell supplies its own masthead, and two
        # titles stacked reads as a mistake.
        lines = text.split("\n")
        if lines and lines[0].startswith("# "):
            lines = lines[1:]
        body = md.render("\n".join(lines))

        # Tables need a scroll wrapper or they blow out the page on a phone.
        body = body.replace("<table>", '<div class="tw"><table>')
        body = body.replace("</table>", "</table></div>")

        dp.write_text(SHELL % {"title": title, "h1": title, "sub": sub,
                               "body": body, "src": src}, encoding="utf-8")
        print("[docs] %s -> %s (%.1f KB)" % (src, dst, dp.stat().st_size / 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
